modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="keephotbaritems" #mandatory
version="1.19.4-1.0.0.0" #mandatory
displayName="Keep Hotbar Items" #mandatory
authors="AAArisle" #optional
description='''Keep your armors and items in hotbar when you die.'''